# SPDX-FileCopyrightText: 2023 Civic Hacker, LLC
# SPDX-License-Identifier: GPL-3.0-or-later
[pytest]
addopts = -p no:warnings
markers =
    v2: tests against the V2 API
python_files = tests.py test_*.py *_tests.py
env_files =
    .env.test
